In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../datasets/zomato_data_raw.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  str
 1   address                      51717 non-null  str
 2   name                         51717 non-null  str
 3   online_order                 51717 non-null  str
 4   book_table                   51717 non-null  str
 5   rate                         43942 non-null  str
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  str
 8   location                     51696 non-null  str
 9   rest_type                    51490 non-null  str
 10  dish_liked                   23639 non-null  str
 11  cuisines                     51672 non-null  str
 12  approx_cost(for two people)  51371 non-null  str
 13  reviews_list                 51717 non-null  str
 14  menu_item                    51717 non-null  str
 15  listed_in(type)              51717 non-null  str
 16  listed_in(city)              51717 non-null  str
dtypes: int64(1), str(16)
memory usage: 552.1 MB

In [2]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [3]:
clean_df = df[['name', 'online_order', 'book_table', 'rate', 'votes', 'location', 'rest_type', 'cuisines', 'listed_in(type)', 'listed_in(city)']]
clean_df.columns = ['Name', 'Online_Order', 'Book_Table', 'Rating', 'Votes', 'Location', 'Restaurant_Type', 'Cuisines', 'Listed_Type', 'Listed_City']
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             51717 non-null  str
 1   Online_Order     51717 non-null  str
 2   Book_Table       51717 non-null  str
 3   Rating           43942 non-null  str
 4   Votes            51717 non-null  int64
 5   Location         51696 non-null  str
 6   Restaurant_Type  51490 non-null  str
 7   Cuisines         51672 non-null  str
 8   Listed_Type      51717 non-null  str
 9   Listed_City      51717 non-null  str
dtypes: int64(1), str(9)
memory usage: 8.6 MB

In [4]:
clean_df = clean_df[clean_df['Rating'] != 'NEW']
clean_df = clean_df.dropna(subset=['Rating', 'Location', 'Restaurant_Type', 'Cuisines'])
clean_df.info()

<class 'pandas.DataFrame'>
Index: 41574 entries, 0 to 51716
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             41574 non-null  str
 1   Online_Order     41574 non-null  str
 2   Book_Table       41574 non-null  str
 3   Rating           41574 non-null  str
 4   Votes            41574 non-null  int64
 5   Location         41574 non-null  str
 6   Restaurant_Type  41574 non-null  str
 7   Cuisines         41574 non-null  str
 8   Listed_Type      41574 non-null  str
 9   Listed_City      41574 non-null  str
dtypes: int64(1), str(9)
memory usage: 7.3 MB

In [5]:
hyphen_ratings = clean_df['Rating'].str.contains('-', na=False)

clean_df = clean_df[~hyphen_ratings]
clean_df.info()

<class 'pandas.DataFrame'>
Index: 41505 entries, 0 to 51716
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             41505 non-null  str
 1   Online_Order     41505 non-null  str
 2   Book_Table       41505 non-null  str
 3   Rating           41505 non-null  str
 4   Votes            41505 non-null  int64
 5   Location         41505 non-null  str
 6   Restaurant_Type  41505 non-null  str
 7   Cuisines         41505 non-null  str
 8   Listed_Type      41505 non-null  str
 9   Listed_City      41505 non-null  str
dtypes: int64(1), str(9)
memory usage: 7.3 MB

In [6]:
clean_df['Online_Order'] = clean_df['Online_Order'].map({
    "Yes": True,
    "No": False
})

clean_df['Book_Table'] = clean_df['Book_Table'].map({
    "Yes": True,
    "No": False
})

clean_df['Rating'] = clean_df['Rating'].str.strip()
clean_df['Rating'] = clean_df['Rating'].str.split('/5').str[0]
clean_df['Rating'] = clean_df['Rating'].str.strip().astype(float)

clean_df

,Name,Online_Order,Book_Table,Rating,Votes,Location,Restaurant_Type,Cuisines,Listed_Type,Listed_City
0,Jalsa,True,True,4.1,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",Buffet,Banashankari
1,Spice Elephant,True,False,4.1,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",Buffet,Banashankari
2,San Churro Cafe,True,False,3.8,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",Buffet,Banashankari
3,Addhuri Udupi Bhojana,False,False,3.7,88,Banashankari,Quick Bites,"South Indian, North Indian",Buffet,Banashankari
4,Grand Village,False,False,3.8,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...
51709,The Farm House Bar n Grill,False,False,3.7,34,Whitefield,"Casual Dining, Bar","North Indian, Continental",Pubs and bars,Whitefield
51711,Bhagini,False,False,2.5,81,Whitefield,"Casual Dining, Bar","Andhra, South Indian, Chinese, North Indian",Pubs and bars,Whitefield
51712,Best Brews - Four Points by Sheraton Bengaluru...,False,False,3.6,27,Whitefield,Bar,Continental,Pubs and bars,Whitefield
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,False,True,4.3,236,"ITPL Main Road, Whitefield",Bar,Finger Food,Pubs and bars,Whitefield
51716,The Nest - The Den Bengaluru,False,False,3.4,13,"ITPL Main Road, Whitefield","Bar, Casual Dining","Finger Food, North Indian, Continental",Pubs and bars,Whitefield

In [7]:
clean_df.to_csv('../datasets/zomato_data_cleaned.csv', index=False)